/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_ilaborie_slides2_RustLib */

#ifndef _Included_io_github_ilaborie_slides2_RustLib
#define _Included_io_github_ilaborie_slides2_RustLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_github_ilaborie_slides2_RustLib
 * Method:    ploper
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_github_ilaborie_slides2_RustLib_ploper
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
